export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Auth } from "./Auth";
export { default as Product } from "./Product";
export { default as Cart } from "./Cart";
export { default as Contact } from "./Contact";
export { default as Error } from "./Error";
export { default as ProductDetail } from "./ProductDetail";
export { default as Wishlist } from "./Wishlist";
